CEDBCN_MonitorIT/Controllers/CasoRobotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CEDBCN_MonitorIT.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CEDBCN_MonitorIT.Controllers
{
    [Route("api/v1/[controller]")]
    public class CasoRobotController : Controller
    {
        private readonly MonitorRobotsDbContext _context;

        public IActionResult Index()
        {
            return View();
        }

        public CasoRobotController(MonitorRobotsDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public List<Caso_Robot> GetAllBook()
        {

            return _context.CasoRobot.Include(c => c.ID_CasoRobot).ToList();
        }
        [HttpGet("{id}")]
        public IActionResult GetByIdBook(int id)
        {

            var result = this._context.CasoRobot.Include(c => c.ID_CasoRobot).SingleOrDefault(t => t.ID_CasoRobot == id);
            if (id == 0)
            {
                return BadRequest();
            }
            else if (result != null)
            {
                return Ok(result);
            }
            else
            {
                return new NoContentResult();
            }
        }
        [HttpPost]
        public IActionResult AddCaso([FromBody] Caso_Robot casos)
        {
            if (!this.ModelState.IsValid)
            {
                return BadRequest();
            }

            this._context.CasoRobot.Add(casos);
            this._context.SaveChanges();
            return Created($"books/{casos.ID_CasoRobot}", casos);
        }
        //[HttpPut("{id}")]
        //public IActionResult updateBooks(int id, [FromBody] Caso_Robot casos)
        //{
        //    var up = this._context.CasoRobot.FirstOrDefault(ct => ct.ID_CasoRobot == id);
        //    if (up == null)
        //    {
        //        return new NoContentResult();
        //    }
        //    else
        //    {
        //        up.Description = books.Description;
        //        up.Genre = books.Genre;
        //        up.Title = books.Title;
        //        up.Section = books.Section;
        //        up.Publisher = books.Publisher;
        //        up.Year = books.Year;

        //        _context.SaveChanges();
        //        return Ok(up);
        //    }
        //}
        [HttpDelete("{id}")]
        public IActionResult DeleteBook(int id)
        {
            var target = _context.CasoRobot.FirstOrDefault(ct => ct.ID_CasoRobot == id);
            if (target == null)
            {
                return NotFound();
            }
            else
            {
                _context.CasoRobot.Remove(target);
                _context.SaveChanges();
                return Ok();
            }
        }
    }
}

CEDBCN_MonitorIT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <link rel="Stylesheet" href="~/css/main.css" />
    <title>@ViewData["Title"] - CEDBCN_MonitorIT</title>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="~/css/materialize.min.css" media="screen,projection" />



    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <!-- Dropdown Structure -->
    <ul id="dropdown1" class="dropdown-content">
        <li><a href="#!">one</a></li>
        <li><a href="#!">two</a></li>
        <li class="divider"></li>
        <li><a href="#!">three</a></li>
    </ul>
    <div class="navbar-fixed-top">
        <nav class="purple darken-1">
            <div class="nav-wrapper">
                @*<a asp-area="" asp-controller="Home" asp-action="Index" class="brand-logo">Logo</a>*@
                <a asp-area="" asp-controller="Home" asp-action="Index" class="bertran-navbar-li-navbar-brand left"><img src="~/images/logo_ced_200.png" class="img-responsive left" />MonitorIT</a>
                <ul class="right hide-on-med-and-down">
                    <li><a class="bertran-navbar-li-Home" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a></li>
                    <li><a class="bertran-navbar-li" asp-area="" asp-controller="Home" asp-action="About">Acerca de</a></li>
                    <li><a class="bertran-navbar-li" asp-area="" asp-controller="Home" asp-action="Contact">Contacto</a></li>
                    <li><a class="bertran-navbar-li" asp-area="" asp-controller="Home" asp-action="EstadoRobots">Estado Robots</a></li>
                    @*<li><a class="bertran-navbar-li" asp-area="" asp-controller="CasoRobot" asp-action="EstadoCasos">Estado Casos</a></li>*@
                    <li>@Html.ActionLink("Listado de casos NO Aperturados", "EstadoCasos", "CasoRobot")</li>
                    <li><a class="bertran-navbar-li" asp-area="" asp-controller="Home" asp-action="EstadoServers">Estado Servers</a></li>
                    <!-- Dropdown Trigger -->
                    <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Menú<i class="material-icons right">--></i></a></li>
                </ul>
            </div>
        </nav>
    </div>
    @*<nav class="navbar navbar-inverse navbar-fixed-top purple">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="bertran-navbar-li-navbar-brand right"><img src="~/images/logo_ced_200.png" class="img-responsive left" />MonitorIT</a>
            </div>*@
    @*
        <div class="navbar-collapse collapse ">
            <ul @*class="nav navbar-nav">@*
    <li><a class="bertran-navbar-li-Home" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a></li>
    <li><a class="bertran-navbar-li" asp-area="" asp-controller="Home" asp-action="About">Acerca de</a></li>
    <li><a class="bertran-navbar-li" asp-area="" asp-controller="Home" asp-action="Contact">Contacto</a></li>
    <li><a class="bertran-navbar-li" asp-area="" asp-controller="Home" asp-action="EstadoRobots">Estado Robots</a></li>
    <li><a class="bertran-navbar-li" asp-area="" asp-controller="Home" asp-action="EstadoCasos">Estado Casos</a></li>
    <li><a class="bertran-navbar-li" asp-area="" asp-controller="Home" asp-action="EstadoServers">Estado Servers</a></li>
    </ul>
    </div>
    </div>
    </nav>*@

    @*<partial name="_CookieConsentPartial" />*@

    <div class="bertran-body">
        @RenderBody()

        <hr />
    </div>
    <div class="container">
        <footer>
            <p>&copy; 2020 - CEDBCN_MonitorIT</p>
        </footer>
    </div>

    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="~/js/materialize.min.js"></script>
    <environment include="Desarrollo">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        @*<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
            </script>*@
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

CEDBCN_MonitorIT/Views/Shared/_Layout_original.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <link rel="Stylesheet" href="~/css/main.css" />
    <title>@ViewData["Title"] - CEDBCN_MonitorIT</title>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="~/css/materialize.min.css" media="screen,projection" />



    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top purple">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="bertran-navbar-li-navbar-brand right"><img src="~/images/logo_ced_200.png" class="img-responsive left" />MonitorIT</a>
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">>
                    <li><a class="bertran-navbar-li-Home" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a></li>
                    <li><a class="bertran-navbar-li" asp-area="" asp-controller="Home" asp-action="About">Acerca de</a></li>
                    <li><a class="bertran-navbar-li" asp-area="" asp-controller="Home" asp-action="Contact">Contacto</a></li>
                    <li><a class="bertran-navbar-li" asp-area="" asp-controller="Home" asp-action="EstadoRobots">Estado Robots</a></li>
                    <li><a class="bertran-navbar-li" asp-area="" asp-controller="Home" asp-action="EstadoCasos">Estado Casos</a></li>
                    <li><a class="bertran-navbar-li" asp-area="" asp-controller="Home" asp-action="EstadoServers">Estado Servers</a></li>
                </ul>
            </div>
        </div>
    </nav>

    @*<partial name="_CookieConsentPartial" />*@

    <div class="container">
        @RenderBody()

    <hr />
    </div>
    <div class="container">
        <footer>
            <p>&copy; 2020 - CEDBCN_MonitorIT</p>
        </footer>
    </div>

    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="~/js/materialize.min.js"></script>
    <environment include="Desarrollo">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        @*<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
            </script>*@
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>